--Insert all nationalities
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (1, 'Afghanistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (2, 'Albania');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (3, 'Algeria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (4, 'Andorra');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (5, 'Angola');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (6, 'Antigua and Barbuda');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (7, 'Argentina');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (8, 'Armenia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (9, 'Australia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (10, 'Austria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (11, 'Azerbaijan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (12, 'Bahamas');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (13, 'Bahrain');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (14, 'Bangladesh');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (15, 'Barbados');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (16, 'Belarus');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (17, 'Belgium');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (18, 'Belize');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (19, 'Benin');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (20, 'Bhutan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (21, 'Bolivia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (22, 'Bosnia and Herzegovina');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (23, 'Botswana');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (24, 'Brazil');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (25, 'Brunei');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (26, 'Bulgaria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (27, 'Burkina Faso');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (28, 'Burundi');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (29, 'Cambodia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (30, 'Cameroon');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (31, 'Canada');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (32, 'Cape Verde');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (33, 'Central African Republic');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (34, 'China');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (35, 'Colombia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (36, 'Comoros');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (37, 'Costa Rica');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (38, 'Croatia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (39, 'Cuba');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (40, 'Cyprus');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (41, 'Czech Republic');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (42, 'Denmark');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (43, 'Djibouti');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (44, 'Dominica');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (45, 'Dominican Republic');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (46, 'East Timor');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (47, 'Ecuador');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (48, 'Egypt');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (49, 'El Salvador');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (50, 'Equatorial Guinea');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (51, 'Eritrea');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (52, 'Estonia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (53, 'Ethiopia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (54, 'Fiji');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (55, 'Finland');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (56, 'France');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (57, 'Gabon');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (58, 'Gambia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (59, 'Georgia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (60, 'Germany');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (61, 'Ghana');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (62, 'Greece');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (63, 'Grenada');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (64, 'Guatemala');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (65, 'Guinea');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (66, 'Guinea-Bissau');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (67, 'Guyana');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (68, 'Haiti');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (69, 'Honduras');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (70, 'Hungary');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (71, 'Iceland');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (72, 'India');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (73, 'Indonesia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (74, 'Iran');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (75, 'Iraq');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (76, 'Ireland');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (77, 'Israel');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (78, 'Italy');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (79, 'Jamaica');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (80, 'Japan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (81, 'Jordan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (82, 'Kazakhstan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (83, 'Kenya');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (84, 'Kiribati');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (85, 'Kuwait');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (86, 'Kyrgyzstan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (87, 'Laos');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (88, 'Latvia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (89, 'Lebanon');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (90, 'Lesotho');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (91, 'Liberia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (92, 'Libya');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (93, 'Liechtenstein');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (94, 'Lithuania');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (95, 'Luxembourg');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (96, 'Madagascar');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (97, 'Malawi');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (98, 'Malaysia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (99, 'Maldives');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (100, 'Mali');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (101, 'Malta');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (102, 'Marshall Islands');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (103, 'Mauritania');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (104, 'Mauritius');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (105, 'Mexico');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (106, 'Micronesia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (107, 'Moldova');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (108, 'Monaco');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (109, 'Mongolia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (110, 'Montenegro');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (111, 'Morocco');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (112, 'Mozambique');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (113, 'Myanmar');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (114, 'Namibia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (115, 'Nauru');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (116, 'Nepal');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (117, 'Netherlands');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (118, 'New Zealand');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (119, 'Nicaragua');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (120, 'Niger');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (121, 'Nigeria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (122, 'North Korea');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (123, 'North Macedonia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (124, 'Norway');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (125, 'Oman');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (126, 'Pakistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (127, 'Palau');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (128, 'Panama');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (129, 'Papua New Guinea');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (130, 'Paraguay');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (131, 'Peru');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (132, 'Philippines');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (133, 'Poland');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (134, 'Portugal');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (135, 'Qatar');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (136, 'Romania');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (137, 'Russia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (138, 'Rwanda');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (139, 'Saint Kitts and Nevis');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (140, 'Saint Lucia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (141, 'Saint Vincent and the Grenadines');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (142, 'Samoa');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (143, 'San Marino');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (144, 'Sao Tome and Principe');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (145, 'Senegal');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (146, 'Serbia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (147, 'Seychelles');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (148, 'Sierra Leone');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (149, 'Singapore');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (150, 'Slovakia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (151, 'Slovenia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (152, 'Solomon Islands');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (153, 'Somalia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (154, 'South Africa');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (155, 'South Sudan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (156, 'Spain');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (157, 'Sri Lanka');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (158, 'Sudan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (159, 'Suriname');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (160, 'Swaziland');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (161, 'Sweden');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (162, 'Switzerland');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (163, 'Syria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (164, 'Taiwan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (165, 'Tajikistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (166, 'Tanzania');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (167, 'Thailand');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (168, 'Togo');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (169, 'Tonga');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (170, 'Trinidad and Tobago');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (171, 'Tunisia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (172, 'Turkey');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (173, 'Turkmenistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (174, 'Tuvalu');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (175, 'Uganda');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (176, 'Ukraine');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (177, 'United Arab Emirates');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (178, 'United Kingdom');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (179, 'United States of America');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (180, 'Uruguay');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (181, 'Uzbekistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (182, 'Vanuatu');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (183, 'Vatican City');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (184, 'Venezuela');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (185, 'Vietnam');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (186, 'Yemen');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (187, 'Zambia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (188, 'Zimbabwe');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (189, 'Unknown');

