--Insert all nationalities
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (1, 'Afghanistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (2, 'Albania');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (3, 'Algeria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (4, 'Andorra');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (5, 'Angola');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (6, 'Antigua and Barbuda');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (7, 'Argentina');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (8, 'Armenia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (9, 'Australia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (10, 'Austria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (11, 'Azerbaijan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (12, 'Bahamas');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (13, 'Bahrain');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (14, 'Bangladesh');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (15, 'Barbados');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (16, 'Belarus');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (17, 'Belgium');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (18, 'Belize');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (19, 'Benin');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (20, 'Bhutan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (21, 'Bolivia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (22, 'Bosnia and Herzegovina');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (23, 'Botswana');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (24, 'Brazil');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (25, 'Brunei');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (26, 'Bulgaria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (27, 'Burkina Faso');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (28, 'Burundi');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (29, 'Cambodia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (30, 'Cameroon');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (31, 'Canada');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (32, 'Cape Verde');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (33, 'Central African Republic');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (34, 'China');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (35, 'Colombie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (36, 'Comores');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (37, 'Congo');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (38, 'Costa Rica');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (39, 'Côte d''Ivoire');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (40, 'Croatie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (41, 'Cuba');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (42, 'Chypre');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (43, 'République tchèque');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (44, 'Danemark');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (45, 'Djibouti');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (46, 'Dominique');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (47, 'République dominicaine');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (48, 'Équateur');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (49, 'Égypte');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (50, 'Salvador');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (51, 'Guinée équatoriale');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (52, 'Érythrée');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (53, 'Estonie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (54, 'Éthiopie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (55, 'Fidji');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (56, 'Finlande');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (57, 'France');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (58, 'Gabon');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (59, 'Gambie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (60, 'Géorgie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (61, 'Allemagne');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (62, 'Ghana');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (63, 'Grèce');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (64, 'Grenade');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (65, 'Guatemala');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (66, 'Guinée');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (67, 'Guinée-Bissau');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (68, 'Guyane');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (69, 'Haïti');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (70, 'Honduras');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (71, 'Hong Kong');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (72, 'Hongrie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (73, 'Île Christmas');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (74, 'Île de Man');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (75, 'Île Norfolk');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (76, 'Îles Caïmans');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (77, 'Îles Cocos');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (78, 'Îles Cook');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (79, 'Îles Féroé');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (80, 'Îles Malouines');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (81, 'Îles Mariannes du Nord');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (82, 'Îles Marshall');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (83, 'Îles Pitcairn');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (84, 'Îles Salomon');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (85, 'Îles Turques-et-Caïques');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (86, 'Îles Vierges britanniques');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (87, 'Îles Vierges des États-Unis');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (88, 'Inde');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (89, 'Indonésie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (90, 'Irak');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (91, 'Iran');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (92, 'Irlande');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (93, 'Islande');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (94, 'Israël');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (95, 'Italie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (96, 'Jamaïque');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (97, 'Japon');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (98, 'Jersey');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (99, 'Jordanie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (100, 'Kazakhstan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (100, 'Kazakhstan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (101, 'Kenya');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (102, 'Kirghizistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (103, 'Kiribati');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (104, 'Koweït');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (105, 'Laos');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (106, 'Lesotho');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (107, 'Lettonie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (108, 'Liban');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (109, 'Liberia');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (110, 'Libye');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (111, 'Liechtenstein');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (112, 'Lituanie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (113, 'Luxembourg');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (114, 'Macédoine');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (115, 'Madagascar');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (116, 'Malaisie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (117, 'Malawi');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (118, 'Maldives');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (119, 'Mali');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (120, 'Malte');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (121, 'Îles Marshall');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (122, 'Mauritanie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (123, 'Maurice');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (124, 'Mexique');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (125, 'Micronésie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (126, 'Moldavie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (127, 'Monaco');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (128, 'Mongolie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (129, 'Monténégro');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (130, 'Maroc');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (131, 'Mozambique');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (132, 'Myanmar');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (133, 'Namibie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (134, 'Nauru');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (135, 'Népal');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (136, 'Nicaragua');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (137, 'Niger');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (138, 'Nigeria');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (139, 'Norvège');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (140, 'Nouvelle-Zélande');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (141, 'Oman');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (142, 'Ouganda');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (143, 'Ouzbékistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (144, 'Pakistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (145, 'Palaos');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (146, 'Panama');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (147, 'Papouasie-Nouvelle-Guinée');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (148, 'Paraguay');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (149, 'Pays-Bas');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (150, 'Pérou');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (151, 'Philippines');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (152, 'Pologne');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (153, 'Portugal');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (154, 'Qatar');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (155, 'République centrafricaine');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (156, 'République démocratique du Congo');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (157, 'République dominicaine');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (158, 'République du Congo');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (159, 'République tchèque');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (160, 'Roumanie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (161, 'Royaume-Uni');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (162, 'Russie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (163, 'Rwanda');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (164, 'Saint-Christophe-et-Niévès');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (165, 'Sainte-Lucie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (166, 'Saint-Marin');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (167, 'Sao Tomé-et-Principe');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (168, 'Sénégal');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (169, 'Serbie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (170, 'Seychelles');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (171, 'Sierra Leone');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (172, 'Singapour');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (173, 'Slovaquie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (174, 'Slovénie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (175, 'Somalie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (176, 'Soudan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (177, 'Soudan du Sud');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (178, 'Sri Lanka');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (179, 'Suède');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (180, 'Suisse');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (181, 'Suriname');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (182, 'Eswatini');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (183, 'Syrie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (184, 'Tadjikistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (185, 'Tanzanie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (186, 'Tchad');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (187, 'République tchèque');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (188, 'Thaïlande');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (189, 'Timor-Leste');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (190, 'Togo');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (191, 'Tonga');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (192, 'Trinité-et-Tobago');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (193, 'Tunisie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (194, 'Turkménistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (195, 'Turquie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (196, 'Tuvalu');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (197, 'Ukraine');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (198, 'Uruguay');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (199, 'Ouzbékistan');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (200, 'Vanuatu');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (201, 'Venezuela');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (202, 'Vietnam');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (203, 'Yémen');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (204, 'Zambie');
INSERT INTO Nationalities (NationalityID, NationalityName) VALUES (205, 'Zimbabwe');



