--Insert all nationalities
INSERT INTO Nationalities (NationalityName) VALUES ('Afghanistan');
INSERT INTO Nationalities (NationalityName) VALUES ('Albania');
INSERT INTO Nationalities (NationalityName) VALUES ('Algeria');
INSERT INTO Nationalities (NationalityName) VALUES ('Andorra');
INSERT INTO Nationalities (NationalityName) VALUES ('Angola');
INSERT INTO Nationalities (NationalityName) VALUES ('Antigua and Barbuda');
INSERT INTO Nationalities (NationalityName) VALUES ('Argentina');
INSERT INTO Nationalities (NationalityName) VALUES ('Armenia');
INSERT INTO Nationalities (NationalityName) VALUES ('Australia');
INSERT INTO Nationalities (NationalityName) VALUES ('Austria');
INSERT INTO Nationalities (NationalityName) VALUES ('Azerbaijan');
INSERT INTO Nationalities (NationalityName) VALUES ('Bahamas');
INSERT INTO Nationalities (NationalityName) VALUES ('Bahrain');
INSERT INTO Nationalities (NationalityName) VALUES ('Bangladesh');
INSERT INTO Nationalities (NationalityName) VALUES ('Barbados');
INSERT INTO Nationalities (NationalityName) VALUES ('Belarus');
INSERT INTO Nationalities (NationalityName) VALUES ('Belgium');
INSERT INTO Nationalities (NationalityName) VALUES ('Belize');
INSERT INTO Nationalities (NationalityName) VALUES ('Benin');
INSERT INTO Nationalities (NationalityName) VALUES ('Bhutan');
INSERT INTO Nationalities (NationalityName) VALUES ('Bolivia');
INSERT INTO Nationalities (NationalityName) VALUES ('Bosnia and Herzegovina');
INSERT INTO Nationalities (NationalityName) VALUES ('Botswana');
INSERT INTO Nationalities (NationalityName) VALUES ('Brazil');
INSERT INTO Nationalities (NationalityName) VALUES ('Brunei');
INSERT INTO Nationalities (NationalityName) VALUES ('Bulgaria');
INSERT INTO Nationalities (NationalityName) VALUES ('Burkina Faso');
INSERT INTO Nationalities (NationalityName) VALUES ('Burundi');
INSERT INTO Nationalities (NationalityName) VALUES ('Cambodia');
INSERT INTO Nationalities (NationalityName) VALUES ('Cameroon');
INSERT INTO Nationalities (NationalityName) VALUES ('Canada');
INSERT INTO Nationalities (NationalityName) VALUES ('Cape Verde');
INSERT INTO Nationalities (NationalityName) VALUES ('Central African Republic');
INSERT INTO Nationalities (NationalityName) VALUES ('China');
INSERT INTO Nationalities (NationalityName) VALUES ('Colombia');
INSERT INTO Nationalities (NationalityName) VALUES ('Comoros');
INSERT INTO Nationalities (NationalityName) VALUES ('Costa Rica');
INSERT INTO Nationalities (NationalityName) VALUES ('Croatia');
INSERT INTO Nationalities (NationalityName) VALUES ('Cuba');
INSERT INTO Nationalities (NationalityName) VALUES ('Cyprus');
INSERT INTO Nationalities (NationalityName) VALUES ('Czech Republic');
INSERT INTO Nationalities (NationalityName) VALUES ('Denmark');
INSERT INTO Nationalities (NationalityName) VALUES ('Djibouti');
INSERT INTO Nationalities (NationalityName) VALUES ('Dominica');
INSERT INTO Nationalities (NationalityName) VALUES ('Dominican Republic');
INSERT INTO Nationalities (NationalityName) VALUES ('East Timor');
INSERT INTO Nationalities (NationalityName) VALUES ('Ecuador');
INSERT INTO Nationalities (NationalityName) VALUES ('Egypt');
INSERT INTO Nationalities (NationalityName) VALUES ('El Salvador');
INSERT INTO Nationalities (NationalityName) VALUES ('Equatorial Guinea');
INSERT INTO Nationalities (NationalityName) VALUES ('Eritrea');
INSERT INTO Nationalities (NationalityName) VALUES ('Estonia');
INSERT INTO Nationalities (NationalityName) VALUES ('Ethiopia');
INSERT INTO Nationalities (NationalityName) VALUES ('Fiji');
INSERT INTO Nationalities (NationalityName) VALUES ('Finland');
INSERT INTO Nationalities (NationalityName) VALUES ('France');
INSERT INTO Nationalities (NationalityName) VALUES ('Gabon');
INSERT INTO Nationalities (NationalityName) VALUES ('Gambia');
INSERT INTO Nationalities (NationalityName) VALUES ('Georgia');
INSERT INTO Nationalities (NationalityName) VALUES ('Germany');
INSERT INTO Nationalities (NationalityName) VALUES ('Ghana');
INSERT INTO Nationalities (NationalityName) VALUES ('Greece');
INSERT INTO Nationalities (NationalityName) VALUES ('Grenada');
INSERT INTO Nationalities (NationalityName) VALUES ('Guatemala');
INSERT INTO Nationalities (NationalityName) VALUES ('Guinea');
INSERT INTO Nationalities (NationalityName) VALUES ('Guinea-Bissau');
INSERT INTO Nationalities (NationalityName) VALUES ('Guyana');
INSERT INTO Nationalities (NationalityName) VALUES ('Haiti');
INSERT INTO Nationalities (NationalityName) VALUES ('Honduras');
INSERT INTO Nationalities (NationalityName) VALUES ('Hungary');
INSERT INTO Nationalities (NationalityName) VALUES ('Iceland');
INSERT INTO Nationalities (NationalityName) VALUES ('India');
INSERT INTO Nationalities (NationalityName) VALUES ('Indonesia');
INSERT INTO Nationalities (NationalityName) VALUES ('Iran');
INSERT INTO Nationalities (NationalityName) VALUES ('Iraq');
INSERT INTO Nationalities (NationalityName) VALUES ('Ireland');
INSERT INTO Nationalities (NationalityName) VALUES ('Israel');
INSERT INTO Nationalities (NationalityName) VALUES ('Italy');
INSERT INTO Nationalities (NationalityName) VALUES ('Jamaica');
INSERT INTO Nationalities (NationalityName) VALUES ('Japan');
INSERT INTO Nationalities (NationalityName) VALUES ('Jordan');
INSERT INTO Nationalities (NationalityName) VALUES ('Kazakhstan');
INSERT INTO Nationalities (NationalityName) VALUES ('Kenya');
INSERT INTO Nationalities (NationalityName) VALUES ('Kiribati');
INSERT INTO Nationalities (NationalityName) VALUES ('Kuwait');
INSERT INTO Nationalities (NationalityName) VALUES ('Kyrgyzstan');
INSERT INTO Nationalities (NationalityName) VALUES ('Laos');
INSERT INTO Nationalities (NationalityName) VALUES ('Latvia');
INSERT INTO Nationalities (NationalityName) VALUES ('Lebanon');
INSERT INTO Nationalities (NationalityName) VALUES ('Lesotho');
INSERT INTO Nationalities (NationalityName) VALUES ('Liberia');
INSERT INTO Nationalities (NationalityName) VALUES ('Libya');
INSERT INTO Nationalities (NationalityName) VALUES ('Liechtenstein');
INSERT INTO Nationalities (NationalityName) VALUES ('Lithuania');
INSERT INTO Nationalities (NationalityName) VALUES ('Luxembourg');
INSERT INTO Nationalities (NationalityName) VALUES ('Madagascar');
INSERT INTO Nationalities (NationalityName) VALUES ('Malawi');
INSERT INTO Nationalities (NationalityName) VALUES ('Malaysia');
INSERT INTO Nationalities (NationalityName) VALUES ('Maldives');
INSERT INTO Nationalities (NationalityName) VALUES ('Mali');
INSERT INTO Nationalities (NationalityName) VALUES ('Malta');
INSERT INTO Nationalities (NationalityName) VALUES ('Marshall Islands');
INSERT INTO Nationalities (NationalityName) VALUES ('Mauritania');
INSERT INTO Nationalities (NationalityName) VALUES ('Mauritius');
INSERT INTO Nationalities (NationalityName) VALUES ('Mexico');
INSERT INTO Nationalities (NationalityName) VALUES ('Micronesia');
INSERT INTO Nationalities (NationalityName) VALUES ('Moldova');
INSERT INTO Nationalities (NationalityName) VALUES ('Monaco');
INSERT INTO Nationalities (NationalityName) VALUES ('Mongolia');
INSERT INTO Nationalities (NationalityName) VALUES ('Montenegro');
INSERT INTO Nationalities (NationalityName) VALUES ('Morocco');
INSERT INTO Nationalities (NationalityName) VALUES ('Mozambique');
INSERT INTO Nationalities (NationalityName) VALUES ('Myanmar');
INSERT INTO Nationalities (NationalityName) VALUES ('Namibia');
INSERT INTO Nationalities (NationalityName) VALUES ('Nauru');
INSERT INTO Nationalities (NationalityName) VALUES ('Nepal');
INSERT INTO Nationalities (NationalityName) VALUES ('Netherlands');
INSERT INTO Nationalities (NationalityName) VALUES ('New Zealand');
INSERT INTO Nationalities (NationalityName) VALUES ('Nicaragua');
INSERT INTO Nationalities (NationalityName) VALUES ('Niger');
INSERT INTO Nationalities (NationalityName) VALUES ('Nigeria');
INSERT INTO Nationalities (NationalityName) VALUES ('North Korea');
INSERT INTO Nationalities (NationalityName) VALUES ('North Macedonia');
INSERT INTO Nationalities (NationalityName) VALUES ('Norway');
INSERT INTO Nationalities (NationalityName) VALUES ('Oman');
INSERT INTO Nationalities (NationalityName) VALUES ('Pakistan');
INSERT INTO Nationalities (NationalityName) VALUES ('Palau');
INSERT INTO Nationalities (NationalityName) VALUES ('Panama');
INSERT INTO Nationalities (NationalityName) VALUES ('Papua New Guinea');
INSERT INTO Nationalities (NationalityName) VALUES ('Paraguay');
INSERT INTO Nationalities (NationalityName) VALUES ('Peru');
INSERT INTO Nationalities (NationalityName) VALUES ('Philippines');
INSERT INTO Nationalities (NationalityName) VALUES ('Poland');
INSERT INTO Nationalities (NationalityName) VALUES ('Portugal');
INSERT INTO Nationalities (NationalityName) VALUES ('Qatar');
INSERT INTO Nationalities (NationalityName) VALUES ('Romania');
INSERT INTO Nationalities (NationalityName) VALUES ('Russia');
INSERT INTO Nationalities (NationalityName) VALUES ('Rwanda');
INSERT INTO Nationalities (NationalityName) VALUES ('Saint Kitts and Nevis');
INSERT INTO Nationalities (NationalityName) VALUES ('Saint Lucia');
INSERT INTO Nationalities (NationalityName) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO Nationalities (NationalityName) VALUES ('Samoa');
INSERT INTO Nationalities (NationalityName) VALUES ('San Marino');
INSERT INTO Nationalities (NationalityName) VALUES ('Sao Tome and Principe');
INSERT INTO Nationalities (NationalityName) VALUES ('Senegal');
INSERT INTO Nationalities (NationalityName) VALUES ('Serbia');
INSERT INTO Nationalities (NationalityName) VALUES ('Seychelles');
INSERT INTO Nationalities (NationalityName) VALUES ('Sierra Leone');
INSERT INTO Nationalities (NationalityName) VALUES ('Singapore');
INSERT INTO Nationalities (NationalityName) VALUES ('Slovakia');
INSERT INTO Nationalities (NationalityName) VALUES ('Slovenia');
INSERT INTO Nationalities (NationalityName) VALUES ('Solomon Islands');
INSERT INTO Nationalities (NationalityName) VALUES ('Somalia');
INSERT INTO Nationalities (NationalityName) VALUES ('South Africa');
INSERT INTO Nationalities (NationalityName) VALUES ('South Sudan');
INSERT INTO Nationalities (NationalityName) VALUES ('Spain');
INSERT INTO Nationalities (NationalityName) VALUES ('Sri Lanka');
INSERT INTO Nationalities (NationalityName) VALUES ('Sudan');
INSERT INTO Nationalities (NationalityName) VALUES ('Suriname');
INSERT INTO Nationalities (NationalityName) VALUES ('Swaziland');
INSERT INTO Nationalities (NationalityName) VALUES ('Sweden');
INSERT INTO Nationalities (NationalityName) VALUES ('Switzerland');
INSERT INTO Nationalities (NationalityName) VALUES ('Syria');
INSERT INTO Nationalities (NationalityName) VALUES ('Taiwan');
INSERT INTO Nationalities (NationalityName) VALUES ('Tajikistan');
INSERT INTO Nationalities (NationalityName) VALUES ('Tanzania');
INSERT INTO Nationalities (NationalityName) VALUES ('Thailand');
INSERT INTO Nationalities (NationalityName) VALUES ('Togo');
INSERT INTO Nationalities (NationalityName) VALUES ('Tonga');
INSERT INTO Nationalities (NationalityName) VALUES ('Trinidad and Tobago');
INSERT INTO Nationalities (NationalityName) VALUES ('Tunisia');
INSERT INTO Nationalities (NationalityName) VALUES ('Turkey');
INSERT INTO Nationalities (NationalityName) VALUES ('Turkmenistan');
INSERT INTO Nationalities (NationalityName) VALUES ('Tuvalu');
INSERT INTO Nationalities (NationalityName) VALUES ('Uganda');
INSERT INTO Nationalities (NationalityName) VALUES ('Ukraine');
INSERT INTO Nationalities (NationalityName) VALUES ('United Arab Emirates');
INSERT INTO Nationalities (NationalityName) VALUES ('United Kingdom');
INSERT INTO Nationalities (NationalityName) VALUES ('United States of America');
INSERT INTO Nationalities (NationalityName) VALUES ('Uruguay');
INSERT INTO Nationalities (NationalityName) VALUES ('Uzbekistan');
INSERT INTO Nationalities (NationalityName) VALUES ('Vanuatu');
INSERT INTO Nationalities (NationalityName) VALUES ('Vatican City');
INSERT INTO Nationalities (NationalityName) VALUES ('Venezuela');
INSERT INTO Nationalities (NationalityName) VALUES ('Vietnam');
INSERT INTO Nationalities (NationalityName) VALUES ('Yemen');
INSERT INTO Nationalities (NationalityName) VALUES ('Zambia');
INSERT INTO Nationalities (NationalityName) VALUES ('Zimbabwe');
INSERT INTO Nationalities (NationalityName) VALUES ('Unknown');

