INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('World Wrestling Entertainment', 'WWE', 179, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('3 Count For McVine', '3CFM', 179, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('All Elite Wrestling', 'AEW', 179, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('New Japan Pro Wrestling', 'NJPW', 80, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('French Wrestling Tournament', 'FWT', 56, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('Extreme Championship Wrestling 2', 'ECW2', 179, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('Lucha Underground', 'LU', 105, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('Evolve Wrestling', 'EW', 179, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('All Pro Wrestling', 'APW', 179, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('Unbeatable Wresting Xtreme', 'UWX', 179, 1)INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('World Wrestling Council', 'WWC', 179, 1)
INSERT INTO Federations (FederationName, FederationAcronym, FederationNationalityID, FederationActive) VALUES ('Maryland Championship Wrestling', 'MCW', 179, 1)
